module.exports = [
    "body > div.wrapper > div:nth-child(2) > div > div.col-sm-6 > div.env-title-municipio",
    // EBAPI - Território e Ambiente
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(1) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(2) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(3) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(4) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(5) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(6) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(7) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(8) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(9) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(10) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(11) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(12) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(13) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(2) > tr:nth-child(14) > td.ebapival",
    // EBAPI - População
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(1) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(2) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(3) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(4) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(5) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(6) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(7) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(8) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(9) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(10) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(11) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(12) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(3) > tr:nth-child(13) > td.ebapival",
    // EBAPI - Socioeconômica
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(1) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(2) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(3) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(4) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(5) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(6) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(7) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(8) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(9) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(10) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(11) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(12) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(13) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(14) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(4) > tr:nth-child(15) > td.ebapival",
    // EBAPI - Saúde e Assistência Social
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(1) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(2) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(3) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(4) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(5) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(6) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(7) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(8) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(9) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(10) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(11) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(12) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(13) > td.ebapival",
    "body > div.wrapper > div.municontent.container-fluid > table > tbody:nth-child(5) > tr:nth-child(14) > td.ebapival",
];