module.exports = [
    "Cidade/Estado",
    // EBAPI
    "Posição Geográfica",
    "Área Territorial",
    "% área urbana no município",
    "Estrutura",
    "Altitude (sede)",
    "Clima",
    "Dias muito quentes (acima de 30°) no ano",
    "Dias muito frios (abaixo de 10°) no ano",
    "Dias com chuva acima de 15mm no ano",
    "Domicílios com esgotamento sanitário",
    "% de domicílios com esgoto a céu aberto",
    "% de vias públicas com arborização",
    "% de vias públicas pavimentadas",
    "% de domicílios urbanos com calçada",
    // EBAPI - População
    "População estimada 2019",
    "Moradores (Censo 2010)",
    "Distribuição da população por gênero",
    "Distribuição dos idosos por gênero",
    "Idade média da população (2010)",
    "Taxa de natalidade (2017)",
    "Número de idosos (2010)",
    "Percentual de idosos (2010)",
    "Índice de envelhecimento (2010)",
    "Evolução do percentual de idosos",
    "Densidade demográfica",
    "Densidade demográfica urbana",
    "Densidade demográfica rural",
    // EBAPI - Socioeconômica
    "População ocupada (2010)",
    "Renda per capita (2010)",
    "Salário médio mensal trabs. formais (2017)",
    "Renda média dos idosos (2010)",
    "Renda média dos idosos em SM (2010)",
    "PIB per capita (2016)",
    "Idosos beneficiários do BPC (dez/2010)",
    "Percentual de idosos beneficiários do BPC (dez/2010)",
    "Idosos beneficiários do BPC (dez/2018)",
    "Idosos em famílias com Bolsa Família (2010)",
    "Percentual de idosos em famílias com Bolsa Família (2010)",
    "Taxa de desemprego (2010)",
    "IDHM (2010)",
    "Escolaridade média (2010)",
    "Fundo de Participação dos Municípios (2018)",
    // EBAPI - Saúde e Assistência Social
    "Óbitos de idosos (2010)",
    "Proporção de óbitos entre idosos (2010)",
    "Principal causa de óbitos de idosos (2010)",
    "Segunda maior causa de óbitos de idosos (2010)",
    "Cobertura Saúde da Família (12/2018)",
    "Coberturas vacinais (2018)",
    "Estabelecimentos SUS atendimento ambulatorial (12/2018)",
    "Estabelecimentos SUS com internação (12/2018)",
    "Estabelecimentos SUS com diagnósticos e terapias (12/2018)",
    "Estabelecimentos SUS com atendimento de urgências (12/2018)",
    "Estabelecimentos SUS de farmácias e cooperativas (12/2018)",
    "Rede socioassistencial com foco no idoso (2018)",
    "Notificações de violência contra o idoso (2017)",
    "Notificações de suicício de idosos (2017)",
];